# Generated by Django 5.2 on 2025-05-02 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=200)),
                ('car_model', models.CharField(max_length=200)),
                ('car_model_year', models.IntegerField()),
                ('car_type', models.CharField(choices=[('Suv', 'SUV'), ('Sed', 'SEDAN'), ('pic', 'PICKUP')], default=(('Suv', 'SUV'), ('Sed', 'SEDAN'), ('pic', 'PICKUP')), max_length=3)),
                ('car_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
