# Generated by Django 5.2 on 2025-05-04 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMaintenanceRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_name', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('Amount', models.FloatField()),
                ('shop_name', models.CharField(max_length=200)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
