# Generated by Django 5.2 on 2025-05-04 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_carmaintenancerecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmaintenancerecords',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='main_app.car'),
        ),
    ]
