# Generated by Django 5.2 on 2025-05-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_carmaintenancerecords_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('suv', 'SUV'), ('sed', 'SEDAN'), ('pic', 'PICKUP')], default=(('suv', 'SUV'), ('sed', 'SEDAN'), ('pic', 'PICKUP')), max_length=3),
        ),
    ]
