# Generated by Django 5.2 on 2025-05-05 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_carmaintenancerecords_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmaintenancerecords',
            old_name='Amount',
            new_name='amount',
        ),
    ]
